# この AWS SAM テンプレートは、関数の設定から生成されました。関数に 1 つ以上のトリガーがある場合は、これらのトリガーに関連付けられている AWS
# リソースがこのテンプレートで完全に指定されておらず、プレースホルダ値も含まれていないことに注意してください。AWS Infrastructure
# Composer またはお気に入りの IDE でこのテンプレートを開き、他の AWS リソースでサーバーレスアプリケーションを指定するように変更します。
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Application Model template describing your function.
Resources:
  staginggroupmessagereminder:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ..
      Description: Send reminder emails for unread group messages
      MemorySize: 512
      Timeout: 300
      Handler: handler.handler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      EphemeralStorage:
        Size: 512
      Environment:
        Variables:
          DATABASE_POOL_SIZE: '5'
          DATABASE_URL: >-
            mysql://admin:dass0707@itasha-staging-mysql-db.cbi8k2qwwj02.ap-northeast-1.rds.amazonaws.com:3306/itashadb
          NODE_ENV: production
          SES_FROM_EMAIL: noreply-staging@itasha-owners-navi.link
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 21600
        MaximumRetryAttempts: 2
      Layers:
        - !Ref Layer1
      PackageType: Zip
      Policies:
        - Statement:
            - Action:
                - ses:SendEmail
                - ses:SendRawEmail
              Resource: '*'
              Effect: Allow
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: '*'
      RecursiveLoop: Terminate
      SnapStart:
        ApplyOn: None
      RuntimeManagementConfig:
        UpdateRuntimeOn: Auto
  # This resource represents your Layer with name staging-prisma-layer. To
# download the content of your Layer, go to
# 
# aws.amazon.com/go/view?arn=arn%3Aaws%3Alambda%3Aap-northeast-1%3A059948105185%3Alayer%3Astaging-prisma-layer%3A4&source=lambda
  Layer1:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: ../../prisma-layer
      LayerName: staging-prisma-layer
      CompatibleRuntimes:
        - nodejs20.x
