AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: WebSocket API for real-time group chat

Parameters:
  Environment:
    Type: String
    Default: dev
    Description: Environment name (dev, staging, prod)
  
  DatabaseUrl:
    Type: String
    Description: RDS Database connection string
    NoEcho: true

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Runtime: nodejs20.x
    Environment:
      Variables:
        DATABASE_URL: !Ref DatabaseUrl
        ENVIRONMENT: !Ref Environment
        CONNECTIONS_TABLE: !Ref ConnectionsTable
        GROUP_ROOMS_TABLE: !Ref GroupRoomsTable

Resources:
  # DynamoDB Table for WebSocket connections
  ConnectionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${Environment}-websocket-connections'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: connectionId
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: connectionId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: userId-index
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true

  # DynamoDB Table for group rooms
  GroupRoomsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${Environment}-websocket-group-rooms'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: groupId
          AttributeType: S
        - AttributeName: connectionId
          AttributeType: S
      KeySchema:
        - AttributeName: groupId
          KeyType: HASH
        - AttributeName: connectionId
          KeyType: RANGE
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true

  # WebSocket API
  WebSocketApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: !Sub '${Environment}-group-chat-websocket'
      ProtocolType: WEBSOCKET
      RouteSelectionExpression: '$request.body.action'
      Description: WebSocket API for real-time group chat

  # WebSocket API Stage
  WebSocketApiStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref WebSocketApi
      StageName: !Sub '${Environment}'
      AutoDeploy: true
      DefaultRouteSettings:
        ThrottlingBurstLimit: 100
        ThrottlingRateLimit: 50

  # Lambda function for WebSocket connect
  WebSocketConnectFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${Environment}-websocket-connect'
      Handler: dist/index.handler
      CodeUri: lambda/websocket-connect/
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ConnectionsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref GroupRoomsTable
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - rds:*
              Resource: '*'
      Events:
        Connect:
          Type: Api
          Properties:
            ApiId: !Ref WebSocketApi
            Route: $connect
            Path: $connect

  # Lambda function for WebSocket disconnect
  WebSocketDisconnectFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${Environment}-websocket-disconnect'
      Handler: dist/index.handler
      CodeUri: lambda/websocket-disconnect/
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ConnectionsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref GroupRoomsTable
      Events:
        Disconnect:
          Type: Api
          Properties:
            ApiId: !Ref WebSocketApi
            Route: $disconnect
            Path: $disconnect

  # Lambda function for join-group route
  WebSocketJoinGroupFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${Environment}-websocket-join-group'
      Handler: dist/index.handler
      CodeUri: lambda/websocket-join-group/
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ConnectionsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref GroupRoomsTable
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - rds:*
              Resource: '*'
      Events:
        JoinGroup:
          Type: Api
          Properties:
            ApiId: !Ref WebSocketApi
            Route: join-group
            Path: join-group

  # Lambda function for leave-group route
  WebSocketLeaveGroupFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${Environment}-websocket-leave-group'
      Handler: dist/index.handler
      CodeUri: lambda/websocket-leave-group/
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ConnectionsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref GroupRoomsTable
      Events:
        LeaveGroup:
          Type: Api
          Properties:
            ApiId: !Ref WebSocketApi
            Route: leave-group
            Path: leave-group

  # Lambda function for send-message route
  WebSocketSendMessageFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${Environment}-websocket-send-message'
      Handler: dist/index.handler
      CodeUri: lambda/websocket-send-message/
      Environment:
        Variables:
          WEBSOCKET_API_ENDPOINT: !Sub 'https://${WebSocketApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}'
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ConnectionsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref GroupRoomsTable
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - execute-api:ManageConnections
              Resource: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${WebSocketApi}/*'
            - Effect: Allow
              Action:
                - rds:*
              Resource: '*'
      Events:
        SendMessage:
          Type: Api
          Properties:
            ApiId: !Ref WebSocketApi
            Route: send-message
            Path: send-message

  # Lambda function for broadcasting messages
  BroadcastMessageFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${Environment}-broadcast-message'
      Handler: dist/index.handler
      CodeUri: lambda/broadcast-message/
      Environment:
        Variables:
          WEBSOCKET_API_ENDPOINT: !Sub 'https://${WebSocketApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}'
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref GroupRoomsTable
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - execute-api:ManageConnections
              Resource: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${WebSocketApi}/*'

Outputs:
  WebSocketApiId:
    Description: WebSocket API ID
    Value: !Ref WebSocketApi
    Export:
      Name: !Sub '${Environment}-websocket-api-id'

  WebSocketApiEndpoint:
    Description: WebSocket API Endpoint
    Value: !Sub 'wss://${WebSocketApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}'
    Export:
      Name: !Sub '${Environment}-websocket-api-endpoint'

  ConnectionsTableName:
    Description: Connections DynamoDB Table Name
    Value: !Ref ConnectionsTable
    Export:
      Name: !Sub '${Environment}-connections-table-name'

  GroupRoomsTableName:
    Description: Group Rooms DynamoDB Table Name
    Value: !Ref GroupRoomsTable
    Export:
      Name: !Sub '${Environment}-group-rooms-table-name'

  BroadcastMessageLambdaArn:
    Description: Broadcast Message Lambda Function ARN
    Value: !GetAtt BroadcastMessageFunction.Arn
    Export:
      Name: !Sub '${Environment}-broadcast-message-lambda-arn'

